name: SlapPlugin
version: ${project.version}
main: me.hassantahan.slapplugin.SlapPlugin
api-version: 1.13
authors: [MrMineHeads]
description: Slaps someone
commands:
  slap:
    description: Slap a dude.
    usage: /<command>
